# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guiPinConfig.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import sys
from lxml import etree as ET

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(849, 567)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 881, 561))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBoxPin_1 = QGroupBox(self.tab)
        self.groupBoxPin_1.setObjectName(u"groupBoxPin_1")
        self.groupBoxPin_1.setGeometry(QRect(10, 10, 401, 111))
        self.dirGroupBox_1 = QGroupBox(self.groupBoxPin_1)
        self.dirGroupBox_1.setObjectName(u"dirGroupBox_1")
        self.dirGroupBox_1.setGeometry(QRect(10, 20, 120, 80))
        self.out_1 = QRadioButton(self.dirGroupBox_1)
        self.out_1.setObjectName(u"out_1")
        self.out_1.setGeometry(QRect(10, 20, 82, 17))
        self.out_1.setChecked(True)
        self.in_1 = QRadioButton(self.dirGroupBox_1)
        self.in_1.setObjectName(u"in_1")
        self.in_1.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_1 = QGroupBox(self.groupBoxPin_1)
        self.pinGroupBox_1.setObjectName(u"pinGroupBox_1")
        self.pinGroupBox_1.setEnabled(False)
        self.pinGroupBox_1.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_1 = QRadioButton(self.pinGroupBox_1)
        self.highImp_1.setObjectName(u"highImp_1")
        self.highImp_1.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_1.setChecked(True)
        self.pullUp_1 = QRadioButton(self.pinGroupBox_1)
        self.pullUp_1.setObjectName(u"pullUp_1")
        self.pullUp_1.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_1 = QGroupBox(self.groupBoxPin_1)
        self.portGroupBox_1.setObjectName(u"portGroupBox_1")
        self.portGroupBox_1.setGeometry(QRect(270, 20, 120, 80))
        self.high_1 = QRadioButton(self.portGroupBox_1)
        self.high_1.setObjectName(u"high_1")
        self.high_1.setGeometry(QRect(10, 20, 82, 17))
        self.high_1.setChecked(True)
        self.low_1 = QRadioButton(self.portGroupBox_1)
        self.low_1.setObjectName(u"low_1")
        self.low_1.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_2 = QGroupBox(self.tab)
        self.groupBoxPin_2.setObjectName(u"groupBoxPin_2")
        self.groupBoxPin_2.setGeometry(QRect(10, 130, 401, 111))
        self.dirGroupBox_2 = QGroupBox(self.groupBoxPin_2)
        self.dirGroupBox_2.setObjectName(u"dirGroupBox_2")
        self.dirGroupBox_2.setGeometry(QRect(10, 20, 120, 80))
        self.out_2 = QRadioButton(self.dirGroupBox_2)
        self.out_2.setObjectName(u"out_2")
        self.out_2.setGeometry(QRect(10, 20, 82, 17))
        self.out_2.setChecked(True)
        self.in_2 = QRadioButton(self.dirGroupBox_2)
        self.in_2.setObjectName(u"in_2")
        self.in_2.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_2 = QGroupBox(self.groupBoxPin_2)
        self.pinGroupBox_2.setObjectName(u"pinGroupBox_2")
        self.pinGroupBox_2.setEnabled(False)
        self.pinGroupBox_2.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_2 = QRadioButton(self.pinGroupBox_2)
        self.highImp_2.setObjectName(u"highImp_2")
        self.highImp_2.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_2.setChecked(True)
        self.pullUp_2 = QRadioButton(self.pinGroupBox_2)
        self.pullUp_2.setObjectName(u"pullUp_2")
        self.pullUp_2.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_2 = QGroupBox(self.groupBoxPin_2)
        self.portGroupBox_2.setObjectName(u"portGroupBox_2")
        self.portGroupBox_2.setGeometry(QRect(270, 20, 120, 80))
        self.high_2 = QRadioButton(self.portGroupBox_2)
        self.high_2.setObjectName(u"high_2")
        self.high_2.setGeometry(QRect(10, 20, 82, 17))
        self.high_2.setChecked(True)
        self.low_2 = QRadioButton(self.portGroupBox_2)
        self.low_2.setObjectName(u"low_2")
        self.low_2.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_3 = QGroupBox(self.tab)
        self.groupBoxPin_3.setObjectName(u"groupBoxPin_3")
        self.groupBoxPin_3.setGeometry(QRect(10, 250, 401, 111))
        self.dirGroupBox_3 = QGroupBox(self.groupBoxPin_3)
        self.dirGroupBox_3.setObjectName(u"dirGroupBox_3")
        self.dirGroupBox_3.setGeometry(QRect(10, 20, 120, 80))
        self.out_3 = QRadioButton(self.dirGroupBox_3)
        self.out_3.setObjectName(u"out_3")
        self.out_3.setGeometry(QRect(10, 20, 82, 17))
        self.out_3.setChecked(True)
        self.in_3 = QRadioButton(self.dirGroupBox_3)
        self.in_3.setObjectName(u"in_3")
        self.in_3.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_3 = QGroupBox(self.groupBoxPin_3)
        self.pinGroupBox_3.setObjectName(u"pinGroupBox_3")
        self.pinGroupBox_3.setEnabled(False)
        self.pinGroupBox_3.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_3 = QRadioButton(self.pinGroupBox_3)
        self.highImp_3.setObjectName(u"highImp_3")
        self.highImp_3.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_3.setChecked(True)
        self.pullUp_3 = QRadioButton(self.pinGroupBox_3)
        self.pullUp_3.setObjectName(u"pullUp_3")
        self.pullUp_3.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_3 = QGroupBox(self.groupBoxPin_3)
        self.portGroupBox_3.setObjectName(u"portGroupBox_3")
        self.portGroupBox_3.setGeometry(QRect(270, 20, 120, 80))
        self.high_3 = QRadioButton(self.portGroupBox_3)
        self.high_3.setObjectName(u"high_3")
        self.high_3.setGeometry(QRect(10, 20, 82, 17))
        self.high_3.setChecked(True)
        self.low_3 = QRadioButton(self.portGroupBox_3)
        self.low_3.setObjectName(u"low_3")
        self.low_3.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_4 = QGroupBox(self.tab)
        self.groupBoxPin_4.setObjectName(u"groupBoxPin_4")
        self.groupBoxPin_4.setGeometry(QRect(10, 370, 401, 111))
        self.dirGroupBox_4 = QGroupBox(self.groupBoxPin_4)
        self.dirGroupBox_4.setObjectName(u"dirGroupBox_4")
        self.dirGroupBox_4.setGeometry(QRect(10, 20, 120, 80))
        self.out_4 = QRadioButton(self.dirGroupBox_4)
        self.out_4.setObjectName(u"out_4")
        self.out_4.setGeometry(QRect(10, 20, 82, 17))
        self.out_4.setChecked(True)
        self.in_4 = QRadioButton(self.dirGroupBox_4)
        self.in_4.setObjectName(u"in_4")
        self.in_4.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_4 = QGroupBox(self.groupBoxPin_4)
        self.pinGroupBox_4.setObjectName(u"pinGroupBox_4")
        self.pinGroupBox_4.setEnabled(False)
        self.pinGroupBox_4.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_4 = QRadioButton(self.pinGroupBox_4)
        self.highImp_4.setObjectName(u"highImp_4")
        self.highImp_4.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_4.setChecked(True)
        self.pullUp_4 = QRadioButton(self.pinGroupBox_4)
        self.pullUp_4.setObjectName(u"pullUp_4")
        self.pullUp_4.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_4 = QGroupBox(self.groupBoxPin_4)
        self.portGroupBox_4.setObjectName(u"portGroupBox_4")
        self.portGroupBox_4.setGeometry(QRect(270, 20, 120, 80))
        self.high_4 = QRadioButton(self.portGroupBox_4)
        self.high_4.setObjectName(u"high_4")
        self.high_4.setGeometry(QRect(10, 20, 82, 17))
        self.high_4.setChecked(True)
        self.low_4 = QRadioButton(self.portGroupBox_4)
        self.low_4.setObjectName(u"low_4")
        self.low_4.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_5 = QGroupBox(self.tab)
        self.groupBoxPin_5.setObjectName(u"groupBoxPin_5")
        self.groupBoxPin_5.setGeometry(QRect(420, 10, 401, 111))
        self.dirGroupBox_5 = QGroupBox(self.groupBoxPin_5)
        self.dirGroupBox_5.setObjectName(u"dirGroupBox_5")
        self.dirGroupBox_5.setGeometry(QRect(10, 20, 120, 80))
        self.out_5 = QRadioButton(self.dirGroupBox_5)
        self.out_5.setObjectName(u"out_5")
        self.out_5.setGeometry(QRect(10, 20, 82, 17))
        self.out_5.setChecked(True)
        self.in_5 = QRadioButton(self.dirGroupBox_5)
        self.in_5.setObjectName(u"in_5")
        self.in_5.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_5 = QGroupBox(self.groupBoxPin_5)
        self.pinGroupBox_5.setObjectName(u"pinGroupBox_5")
        self.pinGroupBox_5.setEnabled(False)
        self.pinGroupBox_5.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_5 = QRadioButton(self.pinGroupBox_5)
        self.highImp_5.setObjectName(u"highImp_5")
        self.highImp_5.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_5.setChecked(True)
        self.pullUp_5 = QRadioButton(self.pinGroupBox_5)
        self.pullUp_5.setObjectName(u"pullUp_5")
        self.pullUp_5.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_5 = QGroupBox(self.groupBoxPin_5)
        self.portGroupBox_5.setObjectName(u"portGroupBox_5")
        self.portGroupBox_5.setGeometry(QRect(270, 20, 120, 80))
        self.high_5 = QRadioButton(self.portGroupBox_5)
        self.high_5.setObjectName(u"high_5")
        self.high_5.setGeometry(QRect(10, 20, 82, 17))
        self.high_5.setChecked(True)
        self.low_5 = QRadioButton(self.portGroupBox_5)
        self.low_5.setObjectName(u"low_5")
        self.low_5.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_6 = QGroupBox(self.tab)
        self.groupBoxPin_6.setObjectName(u"groupBoxPin_6")
        self.groupBoxPin_6.setGeometry(QRect(420, 130, 401, 111))
        self.dirGroupBox_6 = QGroupBox(self.groupBoxPin_6)
        self.dirGroupBox_6.setObjectName(u"dirGroupBox_6")
        self.dirGroupBox_6.setGeometry(QRect(10, 20, 120, 80))
        self.out_6 = QRadioButton(self.dirGroupBox_6)
        self.out_6.setObjectName(u"out_6")
        self.out_6.setGeometry(QRect(10, 20, 82, 17))
        self.out_6.setChecked(True)
        self.in_6 = QRadioButton(self.dirGroupBox_6)
        self.in_6.setObjectName(u"in_6")
        self.in_6.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_6 = QGroupBox(self.groupBoxPin_6)
        self.pinGroupBox_6.setObjectName(u"pinGroupBox_6")
        self.pinGroupBox_6.setEnabled(False)
        self.pinGroupBox_6.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_6 = QRadioButton(self.pinGroupBox_6)
        self.highImp_6.setObjectName(u"highImp_6")
        self.highImp_6.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_6.setChecked(True)
        self.pullUp_6 = QRadioButton(self.pinGroupBox_6)
        self.pullUp_6.setObjectName(u"pullUp_6")
        self.pullUp_6.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_6 = QGroupBox(self.groupBoxPin_6)
        self.portGroupBox_6.setObjectName(u"portGroupBox_6")
        self.portGroupBox_6.setGeometry(QRect(270, 20, 120, 80))
        self.high_6 = QRadioButton(self.portGroupBox_6)
        self.high_6.setObjectName(u"high_6")
        self.high_6.setGeometry(QRect(10, 20, 82, 17))
        self.high_6.setChecked(True)
        self.low_6 = QRadioButton(self.portGroupBox_6)
        self.low_6.setObjectName(u"low_6")
        self.low_6.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_7 = QGroupBox(self.tab)
        self.groupBoxPin_7.setObjectName(u"groupBoxPin_7")
        self.groupBoxPin_7.setGeometry(QRect(420, 250, 401, 111))
        self.dirGroupBox_7 = QGroupBox(self.groupBoxPin_7)
        self.dirGroupBox_7.setObjectName(u"dirGroupBox_7")
        self.dirGroupBox_7.setGeometry(QRect(10, 20, 120, 80))
        self.out_7 = QRadioButton(self.dirGroupBox_7)
        self.out_7.setObjectName(u"out_7")
        self.out_7.setGeometry(QRect(10, 20, 82, 17))
        self.out_7.setChecked(True)
        self.in_7 = QRadioButton(self.dirGroupBox_7)
        self.in_7.setObjectName(u"in_7")
        self.in_7.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_7 = QGroupBox(self.groupBoxPin_7)
        self.pinGroupBox_7.setObjectName(u"pinGroupBox_7")
        self.pinGroupBox_7.setEnabled(False)
        self.pinGroupBox_7.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_7 = QRadioButton(self.pinGroupBox_7)
        self.highImp_7.setObjectName(u"highImp_7")
        self.highImp_7.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_7.setChecked(True)
        self.pullUp_7 = QRadioButton(self.pinGroupBox_7)
        self.pullUp_7.setObjectName(u"pullUp_7")
        self.pullUp_7.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_7 = QGroupBox(self.groupBoxPin_7)
        self.portGroupBox_7.setObjectName(u"portGroupBox_7")
        self.portGroupBox_7.setGeometry(QRect(270, 20, 120, 80))
        self.high_7 = QRadioButton(self.portGroupBox_7)
        self.high_7.setObjectName(u"high_7")
        self.high_7.setGeometry(QRect(10, 20, 82, 17))
        self.high_7.setChecked(True)
        self.low_7 = QRadioButton(self.portGroupBox_7)
        self.low_7.setObjectName(u"low_7")
        self.low_7.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_8 = QGroupBox(self.tab)
        self.groupBoxPin_8.setObjectName(u"groupBoxPin_8")
        self.groupBoxPin_8.setGeometry(QRect(420, 370, 401, 111))
        self.dirGroupBox_8 = QGroupBox(self.groupBoxPin_8)
        self.dirGroupBox_8.setObjectName(u"dirGroupBox_8")
        self.dirGroupBox_8.setGeometry(QRect(10, 20, 120, 80))
        self.out_8 = QRadioButton(self.dirGroupBox_8)
        self.out_8.setObjectName(u"out_8")
        self.out_8.setGeometry(QRect(10, 20, 82, 17))
        self.out_8.setChecked(True)
        self.in_8 = QRadioButton(self.dirGroupBox_8)
        self.in_8.setObjectName(u"in_8")
        self.in_8.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_8 = QGroupBox(self.groupBoxPin_8)
        self.pinGroupBox_8.setObjectName(u"pinGroupBox_8")
        self.pinGroupBox_8.setEnabled(False)
        self.pinGroupBox_8.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_8 = QRadioButton(self.pinGroupBox_8)
        self.highImp_8.setObjectName(u"highImp_8")
        self.highImp_8.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_8.setChecked(True)
        self.pullUp_8 = QRadioButton(self.pinGroupBox_8)
        self.pullUp_8.setObjectName(u"pullUp_8")
        self.pullUp_8.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_8 = QGroupBox(self.groupBoxPin_8)
        self.portGroupBox_8.setObjectName(u"portGroupBox_8")
        self.portGroupBox_8.setGeometry(QRect(270, 20, 120, 80))
        self.high_8 = QRadioButton(self.portGroupBox_8)
        self.high_8.setObjectName(u"high_8")
        self.high_8.setGeometry(QRect(10, 20, 82, 17))
        self.high_8.setChecked(True)
        self.low_8 = QRadioButton(self.portGroupBox_8)
        self.low_8.setObjectName(u"low_8")
        self.low_8.setGeometry(QRect(10, 50, 82, 17))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBoxPin_9 = QGroupBox(self.tab_2)
        self.groupBoxPin_9.setObjectName(u"groupBoxPin_9")
        self.groupBoxPin_9.setGeometry(QRect(10, 10, 401, 111))
        self.dirGroupBox_9 = QGroupBox(self.groupBoxPin_9)
        self.dirGroupBox_9.setObjectName(u"dirGroupBox_9")
        self.dirGroupBox_9.setGeometry(QRect(10, 20, 120, 80))
        self.out_9 = QRadioButton(self.dirGroupBox_9)
        self.out_9.setObjectName(u"out_9")
        self.out_9.setGeometry(QRect(10, 20, 82, 17))
        self.out_9.setChecked(True)
        self.in_9 = QRadioButton(self.dirGroupBox_9)
        self.in_9.setObjectName(u"in_9")
        self.in_9.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_9 = QGroupBox(self.groupBoxPin_9)
        self.pinGroupBox_9.setObjectName(u"pinGroupBox_9")
        self.pinGroupBox_9.setEnabled(False)
        self.pinGroupBox_9.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_9 = QRadioButton(self.pinGroupBox_9)
        self.highImp_9.setObjectName(u"highImp_9")
        self.highImp_9.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_9.setChecked(True)
        self.pullUp_9 = QRadioButton(self.pinGroupBox_9)
        self.pullUp_9.setObjectName(u"pullUp_9")
        self.pullUp_9.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_9 = QGroupBox(self.groupBoxPin_9)
        self.portGroupBox_9.setObjectName(u"portGroupBox_9")
        self.portGroupBox_9.setGeometry(QRect(270, 20, 120, 80))
        self.high_9 = QRadioButton(self.portGroupBox_9)
        self.high_9.setObjectName(u"high_9")
        self.high_9.setGeometry(QRect(10, 20, 82, 17))
        self.high_9.setChecked(True)
        self.low_9 = QRadioButton(self.portGroupBox_9)
        self.low_9.setObjectName(u"low_9")
        self.low_9.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_10 = QGroupBox(self.tab_2)
        self.groupBoxPin_10.setObjectName(u"groupBoxPin_10")
        self.groupBoxPin_10.setGeometry(QRect(10, 130, 401, 111))
        self.dirGroupBox_10 = QGroupBox(self.groupBoxPin_10)
        self.dirGroupBox_10.setObjectName(u"dirGroupBox_10")
        self.dirGroupBox_10.setGeometry(QRect(10, 20, 120, 80))
        self.out_10 = QRadioButton(self.dirGroupBox_10)
        self.out_10.setObjectName(u"out_10")
        self.out_10.setGeometry(QRect(10, 20, 82, 17))
        self.out_10.setChecked(True)
        self.in_10 = QRadioButton(self.dirGroupBox_10)
        self.in_10.setObjectName(u"in_10")
        self.in_10.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_10 = QGroupBox(self.groupBoxPin_10)
        self.pinGroupBox_10.setObjectName(u"pinGroupBox_10")
        self.pinGroupBox_10.setEnabled(False)
        self.pinGroupBox_10.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_10 = QRadioButton(self.pinGroupBox_10)
        self.highImp_10.setObjectName(u"highImp_10")
        self.highImp_10.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_10.setChecked(True)
        self.pullUp_10 = QRadioButton(self.pinGroupBox_10)
        self.pullUp_10.setObjectName(u"pullUp_10")
        self.pullUp_10.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_10 = QGroupBox(self.groupBoxPin_10)
        self.portGroupBox_10.setObjectName(u"portGroupBox_10")
        self.portGroupBox_10.setGeometry(QRect(270, 20, 120, 80))
        self.high_10 = QRadioButton(self.portGroupBox_10)
        self.high_10.setObjectName(u"high_10")
        self.high_10.setGeometry(QRect(10, 20, 82, 17))
        self.high_10.setChecked(True)
        self.low_10 = QRadioButton(self.portGroupBox_10)
        self.low_10.setObjectName(u"low_10")
        self.low_10.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_11 = QGroupBox(self.tab_2)
        self.groupBoxPin_11.setObjectName(u"groupBoxPin_11")
        self.groupBoxPin_11.setGeometry(QRect(10, 250, 401, 111))
        self.dirGroupBox_11 = QGroupBox(self.groupBoxPin_11)
        self.dirGroupBox_11.setObjectName(u"dirGroupBox_11")
        self.dirGroupBox_11.setGeometry(QRect(10, 20, 120, 80))
        self.out_11 = QRadioButton(self.dirGroupBox_11)
        self.out_11.setObjectName(u"out_11")
        self.out_11.setGeometry(QRect(10, 20, 82, 17))
        self.out_11.setChecked(True)
        self.in_11 = QRadioButton(self.dirGroupBox_11)
        self.in_11.setObjectName(u"in_11")
        self.in_11.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_11 = QGroupBox(self.groupBoxPin_11)
        self.pinGroupBox_11.setObjectName(u"pinGroupBox_11")
        self.pinGroupBox_11.setEnabled(False)
        self.pinGroupBox_11.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_11 = QRadioButton(self.pinGroupBox_11)
        self.highImp_11.setObjectName(u"highImp_11")
        self.highImp_11.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_11.setChecked(True)
        self.pullUp_11 = QRadioButton(self.pinGroupBox_11)
        self.pullUp_11.setObjectName(u"pullUp_11")
        self.pullUp_11.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_11 = QGroupBox(self.groupBoxPin_11)
        self.portGroupBox_11.setObjectName(u"portGroupBox_11")
        self.portGroupBox_11.setGeometry(QRect(270, 20, 120, 80))
        self.high_11 = QRadioButton(self.portGroupBox_11)
        self.high_11.setObjectName(u"high_11")
        self.high_11.setGeometry(QRect(10, 20, 82, 17))
        self.high_11.setChecked(True)
        self.low_11 = QRadioButton(self.portGroupBox_11)
        self.low_11.setObjectName(u"low_11")
        self.low_11.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_12 = QGroupBox(self.tab_2)
        self.groupBoxPin_12.setObjectName(u"groupBoxPin_12")
        self.groupBoxPin_12.setGeometry(QRect(10, 370, 401, 111))
        self.dirGroupBox_12 = QGroupBox(self.groupBoxPin_12)
        self.dirGroupBox_12.setObjectName(u"dirGroupBox_12")
        self.dirGroupBox_12.setGeometry(QRect(10, 20, 120, 80))
        self.out_12 = QRadioButton(self.dirGroupBox_12)
        self.out_12.setObjectName(u"out_12")
        self.out_12.setGeometry(QRect(10, 20, 82, 17))
        self.out_12.setChecked(True)
        self.in_12 = QRadioButton(self.dirGroupBox_12)
        self.in_12.setObjectName(u"in_12")
        self.in_12.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_12 = QGroupBox(self.groupBoxPin_12)
        self.pinGroupBox_12.setObjectName(u"pinGroupBox_12")
        self.pinGroupBox_12.setEnabled(False)
        self.pinGroupBox_12.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_12 = QRadioButton(self.pinGroupBox_12)
        self.highImp_12.setObjectName(u"highImp_12")
        self.highImp_12.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_12.setChecked(True)
        self.pullUp_12 = QRadioButton(self.pinGroupBox_12)
        self.pullUp_12.setObjectName(u"pullUp_12")
        self.pullUp_12.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_12 = QGroupBox(self.groupBoxPin_12)
        self.portGroupBox_12.setObjectName(u"portGroupBox_12")
        self.portGroupBox_12.setGeometry(QRect(270, 20, 120, 80))
        self.high_12 = QRadioButton(self.portGroupBox_12)
        self.high_12.setObjectName(u"high_12")
        self.high_12.setGeometry(QRect(10, 20, 82, 17))
        self.high_12.setChecked(True)
        self.low_12 = QRadioButton(self.portGroupBox_12)
        self.low_12.setObjectName(u"low_12")
        self.low_12.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_13 = QGroupBox(self.tab_2)
        self.groupBoxPin_13.setObjectName(u"groupBoxPin_13")
        self.groupBoxPin_13.setGeometry(QRect(420, 10, 401, 111))
        self.dirGroupBox_13 = QGroupBox(self.groupBoxPin_13)
        self.dirGroupBox_13.setObjectName(u"dirGroupBox_13")
        self.dirGroupBox_13.setGeometry(QRect(10, 20, 120, 80))
        self.out_13 = QRadioButton(self.dirGroupBox_13)
        self.out_13.setObjectName(u"out_13")
        self.out_13.setGeometry(QRect(10, 20, 82, 17))
        self.out_13.setChecked(True)
        self.in_13 = QRadioButton(self.dirGroupBox_13)
        self.in_13.setObjectName(u"in_13")
        self.in_13.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_13 = QGroupBox(self.groupBoxPin_13)
        self.pinGroupBox_13.setObjectName(u"pinGroupBox_13")
        self.pinGroupBox_13.setEnabled(False)
        self.pinGroupBox_13.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_13 = QRadioButton(self.pinGroupBox_13)
        self.highImp_13.setObjectName(u"highImp_13")
        self.highImp_13.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_13.setChecked(True)
        self.pullUp_13 = QRadioButton(self.pinGroupBox_13)
        self.pullUp_13.setObjectName(u"pullUp_13")
        self.pullUp_13.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_13 = QGroupBox(self.groupBoxPin_13)
        self.portGroupBox_13.setObjectName(u"portGroupBox_13")
        self.portGroupBox_13.setGeometry(QRect(270, 20, 120, 80))
        self.high_13 = QRadioButton(self.portGroupBox_13)
        self.high_13.setObjectName(u"high_13")
        self.high_13.setGeometry(QRect(10, 20, 82, 17))
        self.high_13.setChecked(True)
        self.low_13 = QRadioButton(self.portGroupBox_13)
        self.low_13.setObjectName(u"low_13")
        self.low_13.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_14 = QGroupBox(self.tab_2)
        self.groupBoxPin_14.setObjectName(u"groupBoxPin_14")
        self.groupBoxPin_14.setGeometry(QRect(420, 130, 401, 111))
        self.dirGroupBox_14 = QGroupBox(self.groupBoxPin_14)
        self.dirGroupBox_14.setObjectName(u"dirGroupBox_14")
        self.dirGroupBox_14.setGeometry(QRect(10, 20, 120, 80))
        self.out_14 = QRadioButton(self.dirGroupBox_14)
        self.out_14.setObjectName(u"out_14")
        self.out_14.setGeometry(QRect(10, 20, 82, 17))
        self.out_14.setChecked(True)
        self.in_14 = QRadioButton(self.dirGroupBox_14)
        self.in_14.setObjectName(u"in_14")
        self.in_14.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_14 = QGroupBox(self.groupBoxPin_14)
        self.pinGroupBox_14.setObjectName(u"pinGroupBox_14")
        self.pinGroupBox_14.setEnabled(False)
        self.pinGroupBox_14.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_14 = QRadioButton(self.pinGroupBox_14)
        self.highImp_14.setObjectName(u"highImp_14")
        self.highImp_14.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_14.setChecked(True)
        self.pullUp_14 = QRadioButton(self.pinGroupBox_14)
        self.pullUp_14.setObjectName(u"pullUp_14")
        self.pullUp_14.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_14 = QGroupBox(self.groupBoxPin_14)
        self.portGroupBox_14.setObjectName(u"portGroupBox_14")
        self.portGroupBox_14.setGeometry(QRect(270, 20, 120, 80))
        self.high_14 = QRadioButton(self.portGroupBox_14)
        self.high_14.setObjectName(u"high_14")
        self.high_14.setGeometry(QRect(10, 20, 82, 17))
        self.high_14.setChecked(True)
        self.low_14 = QRadioButton(self.portGroupBox_14)
        self.low_14.setObjectName(u"low_14")
        self.low_14.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_15 = QGroupBox(self.tab_2)
        self.groupBoxPin_15.setObjectName(u"groupBoxPin_15")
        self.groupBoxPin_15.setGeometry(QRect(420, 250, 401, 111))
        self.dirGroupBox_15 = QGroupBox(self.groupBoxPin_15)
        self.dirGroupBox_15.setObjectName(u"dirGroupBox_15")
        self.dirGroupBox_15.setGeometry(QRect(10, 20, 120, 80))
        self.out_15 = QRadioButton(self.dirGroupBox_15)
        self.out_15.setObjectName(u"out_15")
        self.out_15.setGeometry(QRect(10, 20, 82, 17))
        self.out_15.setChecked(True)
        self.in_15 = QRadioButton(self.dirGroupBox_15)
        self.in_15.setObjectName(u"in_15")
        self.in_15.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_15 = QGroupBox(self.groupBoxPin_15)
        self.pinGroupBox_15.setObjectName(u"pinGroupBox_15")
        self.pinGroupBox_15.setEnabled(False)
        self.pinGroupBox_15.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_15 = QRadioButton(self.pinGroupBox_15)
        self.highImp_15.setObjectName(u"highImp_15")
        self.highImp_15.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_15.setChecked(True)
        self.pullUp_15 = QRadioButton(self.pinGroupBox_15)
        self.pullUp_15.setObjectName(u"pullUp_15")
        self.pullUp_15.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_15 = QGroupBox(self.groupBoxPin_15)
        self.portGroupBox_15.setObjectName(u"portGroupBox_15")
        self.portGroupBox_15.setGeometry(QRect(270, 20, 120, 80))
        self.high_15 = QRadioButton(self.portGroupBox_15)
        self.high_15.setObjectName(u"high_15")
        self.high_15.setGeometry(QRect(10, 20, 82, 17))
        self.high_15.setChecked(True)
        self.low_15 = QRadioButton(self.portGroupBox_15)
        self.low_15.setObjectName(u"low_15")
        self.low_15.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_16 = QGroupBox(self.tab_2)
        self.groupBoxPin_16.setObjectName(u"groupBoxPin_15")
        self.groupBoxPin_16.setGeometry(QRect(420, 370, 401, 111))
        self.dirGroupBox_16 = QGroupBox(self.groupBoxPin_16)
        self.dirGroupBox_16.setObjectName(u"dirGroupBox_16")
        self.dirGroupBox_16.setGeometry(QRect(10, 20, 120, 80))
        self.out_16 = QRadioButton(self.dirGroupBox_16)
        self.out_16.setObjectName(u"out_16")
        self.out_16.setGeometry(QRect(10, 20, 82, 17))
        self.out_16.setChecked(True)
        self.in_16 = QRadioButton(self.dirGroupBox_16)
        self.in_16.setObjectName(u"in_16")
        self.in_16.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_16 = QGroupBox(self.groupBoxPin_16)
        self.pinGroupBox_16.setObjectName(u"pinGroupBox_16")
        self.pinGroupBox_16.setEnabled(False)
        self.pinGroupBox_16.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_16 = QRadioButton(self.pinGroupBox_16)
        self.highImp_16.setObjectName(u"highImp_16")
        self.highImp_16.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_16.setChecked(True)
        self.pullUp_16 = QRadioButton(self.pinGroupBox_16)
        self.pullUp_16.setObjectName(u"pullUp_16")
        self.pullUp_16.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_16 = QGroupBox(self.groupBoxPin_16)
        self.portGroupBox_16.setObjectName(u"portGroupBox_16")
        self.portGroupBox_16.setGeometry(QRect(270, 20, 120, 80))
        self.high_16 = QRadioButton(self.portGroupBox_16)
        self.high_16.setObjectName(u"high_16")
        self.high_16.setGeometry(QRect(10, 20, 82, 17))
        self.high_16.setChecked(True)
        self.low_16 = QRadioButton(self.portGroupBox_16)
        self.low_16.setObjectName(u"low_16")
        self.low_16.setGeometry(QRect(10, 50, 82, 17))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBoxPin_17 = QGroupBox(self.tab_3)
        self.groupBoxPin_17.setObjectName(u"groupBoxPin_17")
        self.groupBoxPin_17.setGeometry(QRect(10, 10, 401, 111))
        self.dirGroupBox_17 = QGroupBox(self.groupBoxPin_17)
        self.dirGroupBox_17.setObjectName(u"dirGroupBox_17")
        self.dirGroupBox_17.setGeometry(QRect(10, 20, 120, 80))
        self.out_17 = QRadioButton(self.dirGroupBox_17)
        self.out_17.setObjectName(u"out_17")
        self.out_17.setGeometry(QRect(10, 20, 82, 17))
        self.out_17.setChecked(True)
        self.in_17 = QRadioButton(self.dirGroupBox_17)
        self.in_17.setObjectName(u"in_17")
        self.in_17.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_17 = QGroupBox(self.groupBoxPin_17)
        self.pinGroupBox_17.setObjectName(u"pinGroupBox_17")
        self.pinGroupBox_17.setEnabled(False)
        self.pinGroupBox_17.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_17 = QRadioButton(self.pinGroupBox_17)
        self.highImp_17.setObjectName(u"highImp_17")
        self.highImp_17.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_17.setChecked(True)
        self.pullUp_17 = QRadioButton(self.pinGroupBox_17)
        self.pullUp_17.setObjectName(u"pullUp_17")
        self.pullUp_17.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_17 = QGroupBox(self.groupBoxPin_17)
        self.portGroupBox_17.setObjectName(u"portGroupBox_17")
        self.portGroupBox_17.setGeometry(QRect(270, 20, 120, 80))
        self.high_17 = QRadioButton(self.portGroupBox_17)
        self.high_17.setObjectName(u"high_17")
        self.high_17.setGeometry(QRect(10, 20, 82, 17))
        self.high_17.setChecked(True)
        self.low_17 = QRadioButton(self.portGroupBox_17)
        self.low_17.setObjectName(u"low_17")
        self.low_17.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_18 = QGroupBox(self.tab_3)
        self.groupBoxPin_18.setObjectName(u"groupBoxPin_18")
        self.groupBoxPin_18.setGeometry(QRect(10, 130, 401, 111))
        self.dirGroupBox_18 = QGroupBox(self.groupBoxPin_18)
        self.dirGroupBox_18.setObjectName(u"dirGroupBox_18")
        self.dirGroupBox_18.setGeometry(QRect(10, 20, 120, 80))
        self.out_18 = QRadioButton(self.dirGroupBox_18)
        self.out_18.setObjectName(u"out_18")
        self.out_18.setGeometry(QRect(10, 20, 82, 17))
        self.out_18.setChecked(True)
        self.in_18 = QRadioButton(self.dirGroupBox_18)
        self.in_18.setObjectName(u"in_18")
        self.in_18.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_18 = QGroupBox(self.groupBoxPin_18)
        self.pinGroupBox_18.setObjectName(u"pinGroupBox_18")
        self.pinGroupBox_18.setEnabled(False)
        self.pinGroupBox_18.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_18 = QRadioButton(self.pinGroupBox_18)
        self.highImp_18.setObjectName(u"highImp_18")
        self.highImp_18.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_18.setChecked(True)
        self.pullUp_18 = QRadioButton(self.pinGroupBox_18)
        self.pullUp_18.setObjectName(u"pullUp_18")
        self.pullUp_18.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_18 = QGroupBox(self.groupBoxPin_18)
        self.portGroupBox_18.setObjectName(u"portGroupBox_18")
        self.portGroupBox_18.setGeometry(QRect(270, 20, 120, 80))
        self.high_18 = QRadioButton(self.portGroupBox_18)
        self.high_18.setObjectName(u"high_18")
        self.high_18.setGeometry(QRect(10, 20, 82, 17))
        self.high_18.setChecked(True)
        self.low_18 = QRadioButton(self.portGroupBox_18)
        self.low_18.setObjectName(u"low_18")
        self.low_18.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_19 = QGroupBox(self.tab_3)
        self.groupBoxPin_19.setObjectName(u"groupBoxPin_19")
        self.groupBoxPin_19.setGeometry(QRect(10, 250, 401, 111))
        self.dirGroupBox_19 = QGroupBox(self.groupBoxPin_19)
        self.dirGroupBox_19.setObjectName(u"dirGroupBox_19")
        self.dirGroupBox_19.setGeometry(QRect(10, 20, 120, 80))
        self.out_19 = QRadioButton(self.dirGroupBox_19)
        self.out_19.setObjectName(u"out_19")
        self.out_19.setGeometry(QRect(10, 20, 82, 17))
        self.out_19.setChecked(True)
        self.in_19 = QRadioButton(self.dirGroupBox_19)
        self.in_19.setObjectName(u"in_19")
        self.in_19.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_19 = QGroupBox(self.groupBoxPin_19)
        self.pinGroupBox_19.setObjectName(u"pinGroupBox_19")
        self.pinGroupBox_19.setEnabled(False)
        self.pinGroupBox_19.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_19 = QRadioButton(self.pinGroupBox_19)
        self.highImp_19.setObjectName(u"highImp_19")
        self.highImp_19.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_19.setChecked(True)
        self.pullUp_19 = QRadioButton(self.pinGroupBox_19)
        self.pullUp_19.setObjectName(u"pullUp_19")
        self.pullUp_19.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_19 = QGroupBox(self.groupBoxPin_19)
        self.portGroupBox_19.setObjectName(u"portGroupBox_19")
        self.portGroupBox_19.setGeometry(QRect(270, 20, 120, 80))
        self.high_19 = QRadioButton(self.portGroupBox_19)
        self.high_19.setObjectName(u"high_19")
        self.high_19.setGeometry(QRect(10, 20, 82, 17))
        self.high_19.setChecked(True)
        self.low_19 = QRadioButton(self.portGroupBox_19)
        self.low_19.setObjectName(u"low_19")
        self.low_19.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_20 = QGroupBox(self.tab_3)
        self.groupBoxPin_20.setObjectName(u"groupBoxPin_20")
        self.groupBoxPin_20.setGeometry(QRect(10, 370, 401, 111))
        self.dirGroupBox_20 = QGroupBox(self.groupBoxPin_20)
        self.dirGroupBox_20.setObjectName(u"dirGroupBox_20")
        self.dirGroupBox_20.setGeometry(QRect(10, 20, 120, 80))
        self.out_20 = QRadioButton(self.dirGroupBox_20)
        self.out_20.setObjectName(u"out_20")
        self.out_20.setGeometry(QRect(10, 20, 82, 17))
        self.out_20.setChecked(True)
        self.in_20 = QRadioButton(self.dirGroupBox_20)
        self.in_20.setObjectName(u"in_20")
        self.in_20.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_20 = QGroupBox(self.groupBoxPin_20)
        self.pinGroupBox_20.setObjectName(u"pinGroupBox_20")
        self.pinGroupBox_20.setEnabled(False)
        self.pinGroupBox_20.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_20 = QRadioButton(self.pinGroupBox_20)
        self.highImp_20.setObjectName(u"highImp_20")
        self.highImp_20.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_20.setChecked(True)
        self.pullUp_20 = QRadioButton(self.pinGroupBox_20)
        self.pullUp_20.setObjectName(u"pullUp_20")
        self.pullUp_20.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_20 = QGroupBox(self.groupBoxPin_20)
        self.portGroupBox_20.setObjectName(u"portGroupBox_24")
        self.portGroupBox_20.setGeometry(QRect(270, 20, 120, 80))
        self.high_20 = QRadioButton(self.portGroupBox_20)
        self.high_20.setObjectName(u"high_20")
        self.high_20.setGeometry(QRect(10, 20, 82, 17))
        self.high_20.setChecked(True)
        self.low_20 = QRadioButton(self.portGroupBox_20)
        self.low_20.setObjectName(u"low_20")
        self.low_20.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_21 = QGroupBox(self.tab_3)
        self.groupBoxPin_21.setObjectName(u"groupBoxPin_21")
        self.groupBoxPin_21.setGeometry(QRect(420, 10, 401, 111))
        self.dirGroupBox_21 = QGroupBox(self.groupBoxPin_21)
        self.dirGroupBox_21.setObjectName(u"dirGroupBox_21")
        self.dirGroupBox_21.setGeometry(QRect(10, 20, 120, 80))
        self.out_21 = QRadioButton(self.dirGroupBox_21)
        self.out_21.setObjectName(u"out_21")
        self.out_21.setGeometry(QRect(10, 20, 82, 17))
        self.out_21.setChecked(True)
        self.in_21 = QRadioButton(self.dirGroupBox_21)
        self.in_21.setObjectName(u"in_21")
        self.in_21.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_21 = QGroupBox(self.groupBoxPin_21)
        self.pinGroupBox_21.setObjectName(u"pinGroupBox_21")
        self.pinGroupBox_21.setEnabled(False)
        self.pinGroupBox_21.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_21 = QRadioButton(self.pinGroupBox_21)
        self.highImp_21.setObjectName(u"highImp_21")
        self.highImp_21.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_21.setChecked(True)
        self.pullUp_21 = QRadioButton(self.pinGroupBox_21)
        self.pullUp_21.setObjectName(u"pullUp_21")
        self.pullUp_21.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_21 = QGroupBox(self.groupBoxPin_21)
        self.portGroupBox_21.setObjectName(u"portGroupBox_21")
        self.portGroupBox_21.setGeometry(QRect(270, 20, 120, 80))
        self.high_21 = QRadioButton(self.portGroupBox_21)
        self.high_21.setObjectName(u"high_21")
        self.high_21.setGeometry(QRect(10, 20, 82, 17))
        self.high_21.setChecked(True)
        self.low_21 = QRadioButton(self.portGroupBox_21)
        self.low_21.setObjectName(u"low_21")
        self.low_21.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_22 = QGroupBox(self.tab_3)
        self.groupBoxPin_22.setObjectName(u"groupBoxPin_22")
        self.groupBoxPin_22.setGeometry(QRect(420, 130, 401, 111))
        self.dirGroupBox_22 = QGroupBox(self.groupBoxPin_22)
        self.dirGroupBox_22.setObjectName(u"dirGroupBox_22")
        self.dirGroupBox_22.setGeometry(QRect(10, 20, 120, 80))
        self.out_22 = QRadioButton(self.dirGroupBox_22)
        self.out_22.setObjectName(u"out_22")
        self.out_22.setGeometry(QRect(10, 20, 82, 17))
        self.out_22.setChecked(True)
        self.in_22 = QRadioButton(self.dirGroupBox_22)
        self.in_22.setObjectName(u"in_22")
        self.in_22.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_22 = QGroupBox(self.groupBoxPin_22)
        self.pinGroupBox_22.setObjectName(u"pinGroupBox_22")
        self.pinGroupBox_22.setEnabled(False)
        self.pinGroupBox_22.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_22 = QRadioButton(self.pinGroupBox_22)
        self.highImp_22.setObjectName(u"highImp_22")
        self.highImp_22.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_22.setChecked(True)
        self.pullUp_22 = QRadioButton(self.pinGroupBox_22)
        self.pullUp_22.setObjectName(u"pullUp_22")
        self.pullUp_22.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_22 = QGroupBox(self.groupBoxPin_22)
        self.portGroupBox_22.setObjectName(u"portGroupBox_26")
        self.portGroupBox_22.setGeometry(QRect(270, 20, 120, 80))
        self.high_22 = QRadioButton(self.portGroupBox_22)
        self.high_22.setObjectName(u"high_22")
        self.high_22.setGeometry(QRect(10, 20, 82, 17))
        self.high_22.setChecked(True)
        self.low_22 = QRadioButton(self.portGroupBox_22)
        self.low_22.setObjectName(u"low_22")
        self.low_22.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_23 = QGroupBox(self.tab_3)
        self.groupBoxPin_23.setObjectName(u"groupBoxPin_23")
        self.groupBoxPin_23.setGeometry(QRect(420, 250, 401, 111))
        self.dirGroupBox_23 = QGroupBox(self.groupBoxPin_23)
        self.dirGroupBox_23.setObjectName(u"dirGroupBox_23")
        self.dirGroupBox_23.setGeometry(QRect(10, 20, 120, 80))
        self.out_23 = QRadioButton(self.dirGroupBox_23)
        self.out_23.setObjectName(u"out_23")
        self.out_23.setGeometry(QRect(10, 20, 82, 17))
        self.out_23.setChecked(True)
        self.in_23 = QRadioButton(self.dirGroupBox_23)
        self.in_23.setObjectName(u"in_23")
        self.in_23.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_23 = QGroupBox(self.groupBoxPin_23)
        self.pinGroupBox_23.setObjectName(u"pinGroupBox_23")
        self.pinGroupBox_23.setEnabled(False)
        self.pinGroupBox_23.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_23 = QRadioButton(self.pinGroupBox_23)
        self.highImp_23.setObjectName(u"highImp_23")
        self.highImp_23.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_23.setChecked(True)
        self.pullUp_23 = QRadioButton(self.pinGroupBox_23)
        self.pullUp_23.setObjectName(u"pullUp_23")
        self.pullUp_23.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_23 = QGroupBox(self.groupBoxPin_23)
        self.portGroupBox_23.setObjectName(u"portGroupBox_23")
        self.portGroupBox_23.setGeometry(QRect(270, 20, 120, 80))
        self.high_23 = QRadioButton(self.portGroupBox_23)
        self.high_23.setObjectName(u"high_23")
        self.high_23.setGeometry(QRect(10, 20, 82, 17))
        self.high_23.setChecked(True)
        self.low_23 = QRadioButton(self.portGroupBox_23)
        self.low_23.setObjectName(u"low_23")
        self.low_23.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_24 = QGroupBox(self.tab_3)
        self.groupBoxPin_24.setObjectName(u"groupBoxPin_24")
        self.groupBoxPin_24.setGeometry(QRect(420, 370, 401, 111))
        self.dirGroupBox_24 = QGroupBox(self.groupBoxPin_24)
        self.dirGroupBox_24.setObjectName(u"dirGroupBox_28")
        self.dirGroupBox_24.setGeometry(QRect(10, 20, 120, 80))
        self.out_24 = QRadioButton(self.dirGroupBox_24)
        self.out_24.setObjectName(u"out_24")
        self.out_24.setGeometry(QRect(10, 20, 82, 17))
        self.out_24.setChecked(True)
        self.in_24 = QRadioButton(self.dirGroupBox_24)
        self.in_24.setObjectName(u"in_24")
        self.in_24.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_24 = QGroupBox(self.groupBoxPin_24)
        self.pinGroupBox_24.setObjectName(u"pinGroupBox_24")
        self.pinGroupBox_24.setEnabled(False)
        self.pinGroupBox_24.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_24 = QRadioButton(self.pinGroupBox_24)
        self.highImp_24.setObjectName(u"highImp_24")
        self.highImp_24.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_24.setChecked(True)
        self.pullUp_24 = QRadioButton(self.pinGroupBox_24)
        self.pullUp_24.setObjectName(u"pullUp_24")
        self.pullUp_24.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_24 = QGroupBox(self.groupBoxPin_24)
        self.portGroupBox_24.setObjectName(u"portGroupBox_28")
        self.portGroupBox_24.setGeometry(QRect(270, 20, 120, 80))
        self.high_24 = QRadioButton(self.portGroupBox_24)
        self.high_24.setObjectName(u"high_24")
        self.high_24.setGeometry(QRect(10, 20, 82, 17))
        self.high_24.setChecked(True)
        self.low_24 = QRadioButton(self.portGroupBox_24)
        self.low_24.setObjectName(u"low_24")
        self.low_24.setGeometry(QRect(10, 50, 82, 17))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBoxPin_25 = QGroupBox(self.tab_4)
        self.groupBoxPin_25.setObjectName(u"groupBoxPin_25")
        self.groupBoxPin_25.setGeometry(QRect(10, 10, 401, 111))
        self.dirGroupBox_25 = QGroupBox(self.groupBoxPin_25)
        self.dirGroupBox_25.setObjectName(u"dirGroupBox_25")
        self.dirGroupBox_25.setGeometry(QRect(10, 20, 120, 80))
        self.out_25 = QRadioButton(self.dirGroupBox_25)
        self.out_25.setObjectName(u"out_25")
        self.out_25.setGeometry(QRect(10, 20, 82, 17))
        self.out_25.setChecked(True)
        self.in_25 = QRadioButton(self.dirGroupBox_25)
        self.in_25.setObjectName(u"in_25")
        self.in_25.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_25 = QGroupBox(self.groupBoxPin_25)
        self.pinGroupBox_25.setObjectName(u"pinGroupBox_29")
        self.pinGroupBox_25.setEnabled(False)
        self.pinGroupBox_25.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_25 = QRadioButton(self.pinGroupBox_25)
        self.highImp_25.setObjectName(u"highImp_25")
        self.highImp_25.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_25.setChecked(True)
        self.pullUp_25 = QRadioButton(self.pinGroupBox_25)
        self.pullUp_25.setObjectName(u"pullUp_25")
        self.pullUp_25.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_25 = QGroupBox(self.groupBoxPin_25)
        self.portGroupBox_25.setObjectName(u"portGroupBox_25")
        self.portGroupBox_25.setGeometry(QRect(270, 20, 120, 80))
        self.high_25 = QRadioButton(self.portGroupBox_25)
        self.high_25.setObjectName(u"high_25")
        self.high_25.setGeometry(QRect(10, 20, 82, 17))
        self.high_25.setChecked(True)
        self.low_25 = QRadioButton(self.portGroupBox_25)
        self.low_25.setObjectName(u"low_25")
        self.low_25.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_26 = QGroupBox(self.tab_4)
        self.groupBoxPin_26.setObjectName(u"groupBoxPin_26")
        self.groupBoxPin_26.setGeometry(QRect(10, 130, 401, 111))
        self.dirGroupBox_26 = QGroupBox(self.groupBoxPin_26)
        self.dirGroupBox_26.setObjectName(u"dirGroupBox_26")
        self.dirGroupBox_26.setGeometry(QRect(10, 20, 120, 80))
        self.out_26 = QRadioButton(self.dirGroupBox_26)
        self.out_26.setObjectName(u"out_26")
        self.out_26.setGeometry(QRect(10, 20, 82, 17))
        self.out_26.setChecked(True)
        self.in_26 = QRadioButton(self.dirGroupBox_26)
        self.in_26.setObjectName(u"in_26")
        self.in_26.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_26 = QGroupBox(self.groupBoxPin_26)
        self.pinGroupBox_26.setObjectName(u"pinGroupBox_26")
        self.pinGroupBox_26.setEnabled(False)
        self.pinGroupBox_26.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_26 = QRadioButton(self.pinGroupBox_26)
        self.highImp_26.setObjectName(u"highImp_26")
        self.highImp_26.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_26.setChecked(True)
        self.pullUp_26 = QRadioButton(self.pinGroupBox_26)
        self.pullUp_26.setObjectName(u"pullUp_26")
        self.pullUp_26.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_26 = QGroupBox(self.groupBoxPin_26)
        self.portGroupBox_26.setObjectName(u"portGroupBox_26")
        self.portGroupBox_26.setGeometry(QRect(270, 20, 120, 80))
        self.high_26 = QRadioButton(self.portGroupBox_26)
        self.high_26.setObjectName(u"high_26")
        self.high_26.setGeometry(QRect(10, 20, 82, 17))
        self.high_26.setChecked(True)
        self.low_26 = QRadioButton(self.portGroupBox_26)
        self.low_26.setObjectName(u"low_26")
        self.low_26.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_27 = QGroupBox(self.tab_4)
        self.groupBoxPin_27.setObjectName(u"groupBoxPin_27")
        self.groupBoxPin_27.setGeometry(QRect(10, 250, 401, 111))
        self.dirGroupBox_27 = QGroupBox(self.groupBoxPin_27)
        self.dirGroupBox_27.setObjectName(u"dirGroupBox_27")
        self.dirGroupBox_27.setGeometry(QRect(10, 20, 120, 80))
        self.out_27 = QRadioButton(self.dirGroupBox_27)
        self.out_27.setObjectName(u"out_27")
        self.out_27.setGeometry(QRect(10, 20, 82, 17))
        self.out_27.setChecked(True)
        self.in_27 = QRadioButton(self.dirGroupBox_27)
        self.in_27.setObjectName(u"in_27")
        self.in_27.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_27 = QGroupBox(self.groupBoxPin_27)
        self.pinGroupBox_27.setObjectName(u"pinGroupBox_31")
        self.pinGroupBox_27.setEnabled(False)
        self.pinGroupBox_27.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_27 = QRadioButton(self.pinGroupBox_27)
        self.highImp_27.setObjectName(u"highImp_27")
        self.highImp_27.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_27.setChecked(True)
        self.pullUp_27 = QRadioButton(self.pinGroupBox_27)
        self.pullUp_27.setObjectName(u"pullUp_27")
        self.pullUp_27.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_27 = QGroupBox(self.groupBoxPin_27)
        self.portGroupBox_27.setObjectName(u"portGroupBox_31")
        self.portGroupBox_27.setGeometry(QRect(270, 20, 120, 80))
        self.high_27 = QRadioButton(self.portGroupBox_27)
        self.high_27.setObjectName(u"high_27")
        self.high_27.setGeometry(QRect(10, 20, 82, 17))
        self.high_27.setChecked(True)
        self.low_27 = QRadioButton(self.portGroupBox_27)
        self.low_27.setObjectName(u"low_27")
        self.low_27.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_28 = QGroupBox(self.tab_4)
        self.groupBoxPin_28.setObjectName(u"groupBoxPin_28")
        self.groupBoxPin_28.setGeometry(QRect(10, 370, 401, 111))
        self.dirGroupBox_28 = QGroupBox(self.groupBoxPin_28)
        self.dirGroupBox_28.setObjectName(u"dirGroupBox_28")
        self.dirGroupBox_28.setGeometry(QRect(10, 20, 120, 80))
        self.out_28 = QRadioButton(self.dirGroupBox_28)
        self.out_28.setObjectName(u"out_28")
        self.out_28.setGeometry(QRect(10, 20, 82, 17))
        self.out_28.setChecked(True)
        self.in_28 = QRadioButton(self.dirGroupBox_28)
        self.in_28.setObjectName(u"in_28")
        self.in_28.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_28 = QGroupBox(self.groupBoxPin_28)
        self.pinGroupBox_28.setObjectName(u"pinGroupBox_28")
        self.pinGroupBox_28.setEnabled(False)
        self.pinGroupBox_28.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_28 = QRadioButton(self.pinGroupBox_28)
        self.highImp_28.setObjectName(u"highImp_28")
        self.highImp_28.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_28.setChecked(True)
        self.pullUp_28 = QRadioButton(self.pinGroupBox_28)
        self.pullUp_28.setObjectName(u"pullUp_28")
        self.pullUp_28.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_28 = QGroupBox(self.groupBoxPin_28)
        self.portGroupBox_28.setObjectName(u"portGroupBox_28")
        self.portGroupBox_28.setGeometry(QRect(270, 20, 120, 80))
        self.high_28 = QRadioButton(self.portGroupBox_28)
        self.high_28.setObjectName(u"high_28")
        self.high_28.setGeometry(QRect(10, 20, 82, 17))
        self.high_28.setChecked(True)
        self.low_28 = QRadioButton(self.portGroupBox_28)
        self.low_28.setObjectName(u"low_28")
        self.low_28.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_29 = QGroupBox(self.tab_4)
        self.groupBoxPin_29.setObjectName(u"groupBoxPin_29")
        self.groupBoxPin_29.setGeometry(QRect(420, 10, 401, 111))
        self.dirGroupBox_29 = QGroupBox(self.groupBoxPin_29)
        self.dirGroupBox_29.setObjectName(u"dirGroupBox_29")
        self.dirGroupBox_29.setGeometry(QRect(10, 20, 120, 80))
        self.out_29 = QRadioButton(self.dirGroupBox_29)
        self.out_29.setObjectName(u"out_29")
        self.out_29.setGeometry(QRect(10, 20, 82, 17))
        self.out_29.setChecked(True)
        self.in_29 = QRadioButton(self.dirGroupBox_29)
        self.in_29.setObjectName(u"in_29")
        self.in_29.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_29 = QGroupBox(self.groupBoxPin_29)
        self.pinGroupBox_29.setObjectName(u"pinGroupBox_29")
        self.pinGroupBox_29.setEnabled(False)
        self.pinGroupBox_29.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_29 = QRadioButton(self.pinGroupBox_29)
        self.highImp_29.setObjectName(u"highImp_29")
        self.highImp_29.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_29.setChecked(True)
        self.pullUp_29 = QRadioButton(self.pinGroupBox_29)
        self.pullUp_29.setObjectName(u"pullUp_29")
        self.pullUp_29.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_29 = QGroupBox(self.groupBoxPin_29)
        self.portGroupBox_29.setObjectName(u"portGroupBox_29")
        self.portGroupBox_29.setGeometry(QRect(270, 20, 120, 80))
        self.high_29 = QRadioButton(self.portGroupBox_29)
        self.high_29.setObjectName(u"high_29")
        self.high_29.setGeometry(QRect(10, 20, 82, 17))
        self.high_29.setChecked(True)
        self.low_29 = QRadioButton(self.portGroupBox_29)
        self.low_29.setObjectName(u"low_29")
        self.low_29.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_30 = QGroupBox(self.tab_4)
        self.groupBoxPin_30.setObjectName(u"groupBoxPin_30")
        self.groupBoxPin_30.setGeometry(QRect(420, 130, 401, 111))
        self.dirGroupBox_30 = QGroupBox(self.groupBoxPin_30)
        self.dirGroupBox_30.setObjectName(u"dirGroupBox_30")
        self.dirGroupBox_30.setGeometry(QRect(10, 20, 120, 80))
        self.out_30 = QRadioButton(self.dirGroupBox_30)
        self.out_30.setObjectName(u"out_30")
        self.out_30.setGeometry(QRect(10, 20, 82, 17))
        self.out_30.setChecked(True)
        self.in_30 = QRadioButton(self.dirGroupBox_30)
        self.in_30.setObjectName(u"in_30")
        self.in_30.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_30 = QGroupBox(self.groupBoxPin_30)
        self.pinGroupBox_30.setObjectName(u"pinGroupBox_30")
        self.pinGroupBox_30.setEnabled(False)
        self.pinGroupBox_30.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_30 = QRadioButton(self.pinGroupBox_30)
        self.highImp_30.setObjectName(u"highImp_30")
        self.highImp_30.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_30.setChecked(True)
        self.pullUp_30 = QRadioButton(self.pinGroupBox_30)
        self.pullUp_30.setObjectName(u"pullUp_30")
        self.pullUp_30.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_30 = QGroupBox(self.groupBoxPin_30)
        self.portGroupBox_30.setObjectName(u"portGroupBox_30")
        self.portGroupBox_30.setGeometry(QRect(270, 20, 120, 80))
        self.high_30 = QRadioButton(self.portGroupBox_30)
        self.high_30.setObjectName(u"high_30")
        self.high_30.setGeometry(QRect(10, 20, 82, 17))
        self.high_30.setChecked(True)
        self.low_30 = QRadioButton(self.portGroupBox_30)
        self.low_30.setObjectName(u"low_30")
        self.low_30.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_31 = QGroupBox(self.tab_4)
        self.groupBoxPin_31.setObjectName(u"groupBoxPin_31")
        self.groupBoxPin_31.setGeometry(QRect(420, 250, 401, 111))
        self.dirGroupBox_31 = QGroupBox(self.groupBoxPin_31)
        self.dirGroupBox_31.setObjectName(u"dirGroupBox_31")
        self.dirGroupBox_31.setGeometry(QRect(10, 20, 120, 80))
        self.out_31 = QRadioButton(self.dirGroupBox_31)
        self.out_31.setObjectName(u"out_31")
        self.out_31.setGeometry(QRect(10, 20, 82, 17))
        self.out_31.setChecked(True)
        self.in_31 = QRadioButton(self.dirGroupBox_31)
        self.in_31.setObjectName(u"in_31")
        self.in_31.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_31 = QGroupBox(self.groupBoxPin_31)
        self.pinGroupBox_31.setObjectName(u"pinGroupBox_31")
        self.pinGroupBox_31.setEnabled(False)
        self.pinGroupBox_31.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_31 = QRadioButton(self.pinGroupBox_31)
        self.highImp_31.setObjectName(u"highImp_31")
        self.highImp_31.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_31.setChecked(True)
        self.pullUp_31 = QRadioButton(self.pinGroupBox_31)
        self.pullUp_31.setObjectName(u"pullUp_31")
        self.pullUp_31.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_31 = QGroupBox(self.groupBoxPin_31)
        self.portGroupBox_31.setObjectName(u"portGroupBox_31")
        self.portGroupBox_31.setGeometry(QRect(270, 20, 120, 80))
        self.high_31 = QRadioButton(self.portGroupBox_31)
        self.high_31.setObjectName(u"high_31")
        self.high_31.setGeometry(QRect(10, 20, 82, 17))
        self.high_31.setChecked(True)
        self.low_31 = QRadioButton(self.portGroupBox_31)
        self.low_31.setObjectName(u"low_31")
        self.low_31.setGeometry(QRect(10, 50, 82, 17))
        self.groupBoxPin_32 = QGroupBox(self.tab_4)
        self.groupBoxPin_32.setObjectName(u"groupBoxPin_32")
        self.groupBoxPin_32.setGeometry(QRect(420, 370, 401, 111))
        self.dirGroupBox_32 = QGroupBox(self.groupBoxPin_32)
        self.dirGroupBox_32.setObjectName(u"dirGroupBox_32")
        self.dirGroupBox_32.setGeometry(QRect(10, 20, 120, 80))
        self.out_32 = QRadioButton(self.dirGroupBox_32)
        self.out_32.setObjectName(u"out_32")
        self.out_32.setGeometry(QRect(10, 20, 82, 17))
        self.out_32.setChecked(True)
        self.in_32 = QRadioButton(self.dirGroupBox_32)
        self.in_32.setObjectName(u"in_32")
        self.in_32.setGeometry(QRect(10, 50, 82, 17))
        self.pinGroupBox_32 = QGroupBox(self.groupBoxPin_32)
        self.pinGroupBox_32.setObjectName(u"pinGroupBox_32")
        self.pinGroupBox_32.setEnabled(False)
        self.pinGroupBox_32.setGeometry(QRect(140, 20, 120, 80))
        self.highImp_32 = QRadioButton(self.pinGroupBox_32)
        self.highImp_32.setObjectName(u"highImp_32")
        self.highImp_32.setGeometry(QRect(10, 20, 82, 17))
        self.highImp_32.setChecked(True)
        self.pullUp_32 = QRadioButton(self.pinGroupBox_32)
        self.pullUp_32.setObjectName(u"pullUp_32")
        self.pullUp_32.setGeometry(QRect(10, 50, 82, 17))
        self.portGroupBox_32 = QGroupBox(self.groupBoxPin_32)
        self.portGroupBox_32.setObjectName(u"portGroupBox_32")
        self.portGroupBox_32.setGeometry(QRect(270, 20, 120, 80))
        self.high_32 = QRadioButton(self.portGroupBox_32)
        self.high_32.setObjectName(u"high_32")
        self.high_32.setGeometry(QRect(10, 20, 82, 17))
        self.high_32.setChecked(True)
        self.low_32 = QRadioButton(self.portGroupBox_32)
        self.low_32.setObjectName(u"low_32")
        self.low_32.setGeometry(QRect(10, 50, 82, 17))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.lineEdit_generate = QLineEdit(self.tab_5)
        self.lineEdit_generate.setObjectName(u"lineEdit_generate")
        self.lineEdit_generate.setGeometry(QRect(130, 180, 301, 21))
        self.lineEdit_save = QLineEdit(self.tab_5)
        self.lineEdit_save.setObjectName(u"lineEdit_save")
        self.lineEdit_save.setGeometry(QRect(130, 220, 301, 21))
        self.generatePushBtn = QPushButton(self.tab_5)
        self.generatePushBtn.setObjectName(u"generatePushBtn")
        self.generatePushBtn.setGeometry(QRect(460, 180, 75, 23))
        self.savePushBtn = QPushButton(self.tab_5)
        self.savePushBtn.setObjectName(u"savePushBtn")
        self.savePushBtn.setGeometry(QRect(460, 220, 75, 23))
        self.loadPushBtn = QPushButton(self.tab_5)
        self.loadPushBtn.setObjectName(u"loadPushBtn")
        self.loadPushBtn.setGeometry(QRect(460, 260, 75, 23))
        self.lineEdit_load = QLineEdit(self.tab_5)
        self.lineEdit_load.setObjectName(u"lineEdit_load")
        self.lineEdit_load.setGeometry(QRect(130, 260, 301, 21))
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)
        
        self.generatePushBtn.clicked.connect(self.generateFunction)
        self.savePushBtn.clicked.connect(self.saveFunction)
        self.loadPushBtn.clicked.connect(self.loadFunction)

        for index in range(1, 33):
          outRadioBtn = 'out_%d' % index
          InpRadioBtn = 'in_%d' % index
          pinGroupBox = 'pinGroupBox_%d' % index
          portGroupBox = 'portGroupBox_%d' % index

          QObject.connect(getattr(self, outRadioBtn),SIGNAL("clicked(bool)"),getattr(self, pinGroupBox).setDisabled)
          QObject.connect(getattr(self, outRadioBtn),SIGNAL("clicked(bool)"),getattr(self, portGroupBox).setEnabled)
          QObject.connect(getattr(self, InpRadioBtn),SIGNAL("clicked(bool)"),getattr(self, portGroupBox).setDisabled)
          QObject.connect(getattr(self, InpRadioBtn),SIGNAL("clicked(bool)"),getattr(self, pinGroupBox).setEnabled)




        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def generateFunction(self):
      
      Output_Path = self.lineEdit_generate.text() + r'\DIO_Config.h'
      File_Handler = open(Output_Path ,'w')
      File_Handler.write("#ifndef DIO_CONFIG_H_\n")
      File_Handler.write("#define DIO_CONFIG_H_\n")
      File_Handler.write("\n")
      File_Handler.write("\n")
      File_Handler.write("#endif /* DIO_CONFIG_H_ */\n")

      for index in range(1, 33):
        outRadioBtn = 'out_%d' % index
        highRadioBtn = 'high_%d' % index
        pullUpRadioBtn = 'pullUp_%d' % index
        
        getattr(self, pullUpRadioBtn)
        if getattr(self, outRadioBtn).isChecked():
          if getattr(self, highRadioBtn).isChecked():
            File_Handler.write("#define DIO_PIN_"+str(index-1)+"_MODE	DIO_OUTPUT_HIGH\n")
          else:
            File_Handler.write("#define DIO_PIN_"+str(index-1)+"_MODE	DIO_OUTPUT_LOW\n")
        else:
          if getattr(self, pullUpRadioBtn).isChecked():
            File_Handler.write("#define DIO_PIN_"+str(index-1)+"_MODE	DIO_INPUT_PULLED_UP\n")
          else:
            File_Handler.write("#define DIO_PIN_"+str(index-1)+"_MODE	DIO_INPUT_HIGH_IMP\n")

      File_Handler.write("#endif /* DIO_CONFIG_H */ \n")
        
    def saveFunction(self):
      DIO = ET.Element("DIO")
      
      for index in range(1, 33):
        print(index)
        
        PIN = ET.Element("PIN"+str(index))
        DIR = ET.Element("DIR")
        CONFIG = ET.Element("CONFIG")
        
        outRadioBtn = 'out_%d' % index
        highRadioBtn = 'high_%d' % index
        pullUpRadioBtn = 'pullUp_%d' % index
        
        if getattr(self, outRadioBtn).isChecked():
          DIR.text='OUTPUT'
          if getattr(self, highRadioBtn).isChecked():
            CONFIG.text='HIGH'
          else:
            CONFIG.text='LOW'
        else:
          DIR.text='INPUT'
          if getattr(self, pullUpRadioBtn).isChecked():
            CONFIG.text='PULL-UP'
          else:
            CONFIG.text='HIGH-IMP'

        DIO.append(PIN)
        PIN.append(DIR)
        PIN.append(CONFIG)
        print(ET.tostring(DIO, pretty_print=True).decode())

      path = self.lineEdit_save.text()+r'\DIO_Cfg.xml'
      File_Handler=open(path,'w')
      File_Handler.write(ET.tostring(DIO, pretty_print=True).decode())
      File_Handler.close()
  
    def loadFunction(self):
      path= self.lineEdit_load.text()+r'\DIO_Cfg.xml'
      tree = ET.parse(path)
      DIO=tree.getroot()
      for index in range(1, 33):
        outRadioBtn = 'out_%d' % index
        highRadioBtn = 'high_%d' % index
        pullUpRadioBtn = 'pullUp_%d' % index
        InpRadioBtn = 'in_%d' % index
        pinGroupBox = 'pinGroupBox_%d' % index
        portGroupBox = 'portGroupBox_%d' % index
        highImpRadioBtn = 'highImp_%d' % index
        lowRadioBtn = 'low_%d' % index
        
        PIN=DIO.find("PIN"+str(index))
        DIR = PIN.find('DIR').text
        CONFIG = PIN.find('CONFIG').text
        if DIR=="INPUT":
          getattr(self, InpRadioBtn).setChecked(True)
          getattr(self, portGroupBox).setDisabled(True)
          getattr(self, pinGroupBox).setEnabled(True)
          if CONFIG == "PULL-UP":
            getattr(self, pullUpRadioBtn).setChecked(True)
          else:
            getattr(self, highImpRadioBtn).setChecked(True)
        else:
          getattr(self, outRadioBtn).setChecked(True)
          getattr(self, pinGroupBox).setDisabled(True)
          getattr(self, portGroupBox).setEnabled(True)
          if CONFIG == "LOW":
            getattr(self, lowRadioBtn).setChecked(True)
          else:
            getattr(self, highRadioBtn).setChecked(True)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.groupBoxPin_1.setTitle(QCoreApplication.translate("Form", u"PIN0", None))
        self.dirGroupBox_1.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_1.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_1.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_1.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_1.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_1.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_1.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_1.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_1.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_2.setTitle(QCoreApplication.translate("Form", u"PIN1", None))
        self.dirGroupBox_2.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_2.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_2.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_2.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_2.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_2.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_2.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_2.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_2.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_3.setTitle(QCoreApplication.translate("Form", u"PIN2", None))
        self.dirGroupBox_3.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_3.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_3.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_3.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_3.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_3.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_3.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_3.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_3.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_4.setTitle(QCoreApplication.translate("Form", u"PIN3", None))
        self.dirGroupBox_4.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_4.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_4.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_4.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_4.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_4.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_4.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_4.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_4.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_5.setTitle(QCoreApplication.translate("Form", u"PIN4", None))
        self.dirGroupBox_5.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_5.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_5.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_5.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_5.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_5.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_5.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_5.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_5.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_6.setTitle(QCoreApplication.translate("Form", u"PIN5", None))
        self.dirGroupBox_6.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_6.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_6.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_6.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_6.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_6.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_6.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_6.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_6.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_7.setTitle(QCoreApplication.translate("Form", u"PIN6", None))
        self.dirGroupBox_7.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_7.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_7.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_7.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_7.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_7.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_7.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_7.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_7.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_8.setTitle(QCoreApplication.translate("Form", u"PIN7", None))
        self.dirGroupBox_8.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_8.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_8.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_8.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_8.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_8.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_8.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_8.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_8.setText(QCoreApplication.translate("Form", u"Low", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Tab 1", None))
        self.groupBoxPin_9.setTitle(QCoreApplication.translate("Form", u"PIN8", None))
        self.dirGroupBox_9.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_9.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_9.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_9.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_9.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_9.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_9.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_9.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_9.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_10.setTitle(QCoreApplication.translate("Form", u"PIN9", None))
        self.dirGroupBox_10.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_10.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_10.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_10.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_10.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_10.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_10.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_10.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_10.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_11.setTitle(QCoreApplication.translate("Form", u"PIN10", None))
        self.dirGroupBox_11.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_11.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_11.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_11.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_11.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_11.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_11.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_11.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_11.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_12.setTitle(QCoreApplication.translate("Form", u"PIN11", None))
        self.dirGroupBox_12.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_12.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_12.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_12.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_12.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_12.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_12.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_12.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_12.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_13.setTitle(QCoreApplication.translate("Form", u"PIN12", None))
        self.dirGroupBox_13.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_13.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_13.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_13.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_13.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_13.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_13.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_13.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_13.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_14.setTitle(QCoreApplication.translate("Form", u"PIN13", None))
        self.dirGroupBox_14.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_14.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_14.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_14.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_14.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_14.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_14.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_14.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_14.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_15.setTitle(QCoreApplication.translate("Form", u"PIN14", None))
        self.dirGroupBox_15.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_15.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_15.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_15.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_15.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_15.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_15.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_15.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_15.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_16.setTitle(QCoreApplication.translate("Form", u"PIN15", None))
        self.dirGroupBox_16.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_16.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_16.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_16.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_16.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_16.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_16.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_16.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_16.setText(QCoreApplication.translate("Form", u"Low", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"Tab 2", None))
        self.groupBoxPin_17.setTitle(QCoreApplication.translate("Form", u"PIN16", None))
        self.dirGroupBox_17.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_17.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_17.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_17.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_17.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_17.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_17.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_17.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_17.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_18.setTitle(QCoreApplication.translate("Form", u"PIN17", None))
        self.dirGroupBox_18.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_18.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_18.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_18.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_18.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_18.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_18.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_18.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_18.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_19.setTitle(QCoreApplication.translate("Form", u"PIN18", None))
        self.dirGroupBox_19.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_19.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_19.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_19.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_19.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_19.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_19.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_19.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_19.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_20.setTitle(QCoreApplication.translate("Form", u"PIN19", None))
        self.dirGroupBox_20.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_20.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_20.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_20.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_20.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_20.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_20.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_20.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_20.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_21.setTitle(QCoreApplication.translate("Form", u"PIN20", None))
        self.dirGroupBox_21.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_21.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_21.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_21.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_21.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_21.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_21.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_21.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_21.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_22.setTitle(QCoreApplication.translate("Form", u"PIN21", None))
        self.dirGroupBox_22.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_22.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_22.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_22.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_22.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_22.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_22.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_22.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_22.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_23.setTitle(QCoreApplication.translate("Form", u"PIN22", None))
        self.dirGroupBox_23.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_23.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_23.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_23.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_23.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_23.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_23.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_23.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_23.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_24.setTitle(QCoreApplication.translate("Form", u"PIN23", None))
        self.dirGroupBox_24.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_24.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_24.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_24.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_24.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_24.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_24.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_24.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_24.setText(QCoreApplication.translate("Form", u"Low", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Form", u"Tab 3", None))
        self.groupBoxPin_25.setTitle(QCoreApplication.translate("Form", u"PIN24", None))
        self.dirGroupBox_25.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_25.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_25.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_25.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_25.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_25.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_25.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_25.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_25.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_26.setTitle(QCoreApplication.translate("Form", u"PIN25", None))
        self.dirGroupBox_26.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_26.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_26.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_26.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_26.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_26.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_26.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_26.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_26.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_27.setTitle(QCoreApplication.translate("Form", u"PIN26", None))
        self.dirGroupBox_27.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_27.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_27.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_27.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_27.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_27.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_27.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_27.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_27.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_28.setTitle(QCoreApplication.translate("Form", u"PIN27", None))
        self.dirGroupBox_28.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_28.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_28.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_28.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_28.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_28.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_28.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_28.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_28.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_29.setTitle(QCoreApplication.translate("Form", u"PIN28", None))
        self.dirGroupBox_29.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_29.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_29.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_29.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_29.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_29.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_29.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_29.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_29.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_30.setTitle(QCoreApplication.translate("Form", u"PIN29", None))
        self.dirGroupBox_30.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_30.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_30.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_30.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_30.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_30.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_30.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_30.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_30.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_31.setTitle(QCoreApplication.translate("Form", u"PIN30", None))
        self.dirGroupBox_31.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_31.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_31.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_31.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_31.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_31.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_31.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_31.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_31.setText(QCoreApplication.translate("Form", u"Low", None))
        self.groupBoxPin_32.setTitle(QCoreApplication.translate("Form", u"PIN31", None))
        self.dirGroupBox_32.setTitle(QCoreApplication.translate("Form", u"Direction", None))
        self.out_32.setText(QCoreApplication.translate("Form", u"Output", None))
        self.in_32.setText(QCoreApplication.translate("Form", u"Input", None))
        self.pinGroupBox_32.setTitle(QCoreApplication.translate("Form", u"PIN", None))
        self.highImp_32.setText(QCoreApplication.translate("Form", u"High-imp", None))
        self.pullUp_32.setText(QCoreApplication.translate("Form", u"Pull-Up", None))
        self.portGroupBox_32.setTitle(QCoreApplication.translate("Form", u"PORT", None))
        self.high_32.setText(QCoreApplication.translate("Form", u"High", None))
        self.low_32.setText(QCoreApplication.translate("Form", u"Low", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Form", u"Tab 4", None))
        self.generatePushBtn.setText(QCoreApplication.translate("Form", u"Generate", None))
        self.savePushBtn.setText(QCoreApplication.translate("Form", u"Save", None))
        self.loadPushBtn.setText(QCoreApplication.translate("Form", u"Load", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Form", u"Page", None))
    # retranslateUi

app=QApplication(sys.argv)
Widget=QWidget()
Form=Ui_Form()
Form.setupUi(Widget)
Widget.show()
sys.exit(app.exec_())